name: mouseflow_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # CUDA-enabled PyTorch from conda
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - numpy>=2
  - h5py
  - pytables>=3.9.2
  - ffmpeg
  - scipy
  - pandas
  - pip
  - pip:
      - pyocclient # for downloading owncloud files

  # Install DLC manually(!!)
  # (not in this file because the pre release version is needed for pytorch support) via:
  # pip install --pre deeplabcut